default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PSQL_USER"] %>
  password: <%= ENV["PSQL_PASS"] %>
  host: <%= ENV["PSQL_HOST"] %>
  timeout: 5000

development:
  <<: *default
  database: how_crowded_is_it_development

test:
  <<: *default
  database: how_crowded_is_it_test

production:
  <<: *default
  database: how_crowded_is_it_development_production
